- repoName: flathub
  repoUrl: https://dl.flathub.org/repo/
  apps:
    - com.github.tchx84.Flatseal
    - com.saivert.pwvucontrol
    - com.spotify.Client
    - com.usebottles.bottles
    - net.waterfox.waterfox
    - org.gnome.dspy
    - org.remmina.Remmina
    - org.mozilla.Thunderbird
