7zip:
bind:
ddcutil:
docker:
docker-compose:
eza:
fd:
fish:
git:
  - openssh
go:
go-yq:
htop:
  - lsof
  - strace
hyperfine:
imv:
jq:
neovim:
  - wl-clipboard
net-tools:
nodejs:
  - npm
pacman-contrib:
  - fakeroot
pass:
playerctl:
pwgen:
python:
python-pip:
python-pipx:
python-virtualenv:
qrencode:
rclone:
  - fuse3
reflector:
ripgrep:
rsync:
rustup:
starship:
the_silver_searcher:
tmux:
tree:
unrar:
unzip:
usbutils:
uv:
wget:
wine:
  - wine-gecko
  - wine-mono
winetricks:
zbar:
  - gtk3
zenity:
zig:
